services:
  db:
    image: postgres:17.6-alpine3.22
    restart: unless-stopped
    ports:
      - 15432:5432
    volumes:
      - ./migrations/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 5
  rabbitmq:
    image: rabbitmq:4.2-management
    restart: unless-stopped
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=devuser
      - RABBITMQ_DEFAULT_PASS=devpassword
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 10s
      timeout: 30s
      retries: 5
